"""
Quick test script for AI-Native HR Agent
Run this to verify the implementation works
"""

import sys
import time

def test_ai_native():
    print("🧪 Testing AI-Native HR Agent")
    print("=" * 60)
    
    # Test 1: Import
    print("\n1️⃣ Testing imports...")
    try:
        from hr_agent_ai_native import AINativeHRAgent, AIStrategicInsights
        from data_loader import load_candidates, create_job_from_dataset
        print("   ✅ Imports successful")
    except ImportError as e:
        print(f"   ❌ Import failed: {e}")
        return False
    
    # Test 2: Load data
    print("\n2️⃣ Loading test data...")
    try:
        candidates = load_candidates("data/resume_dataset_1200.csv")[:50]
        jd = create_job_from_dataset("data/resume_dataset_1200.csv")
        print(f"   ✅ Loaded {len(candidates)} candidates")
        print(f"   ✅ Job: {jd.title}")
    except Exception as e:
        print(f"   ❌ Data loading failed: {e}")
        return False
    
    # Test 3: Initialize agent
    print("\n3️⃣ Initializing AI-Native agent...")
    try:
        agent = AINativeHRAgent(use_llm=True)
        print("   ✅ Agent initialized")
    except Exception as e:
        print(f"   ❌ Agent initialization failed: {e}")
        return False
    
    # Test 4: Screen resumes
    print("\n4️⃣ Screening resumes with AI insights...")
    try:
        start = time.time()
        ranked = agent.screen_resumes(candidates, jd)
        elapsed = time.time() - start
        print(f"   ✅ Screened {len(ranked)} candidates in {elapsed:.2f}s")
    except Exception as e:
        print(f"   ❌ Screening failed: {e}")
        return False
    
    # Test 5: Executive Summary
    print("\n5️⃣ Checking Executive Summary...")
    try:
        assert agent.executive_summary is not None, "Executive summary is None"
        assert 'summary' in agent.executive_summary, "Missing summary field"
        assert 'key_findings' in agent.executive_summary, "Missing key_findings"
        assert 'recommendations' in agent.executive_summary, "Missing recommendations"
        
        print("   ✅ Executive Summary generated")
        print(f"   📊 Confidence: {agent.executive_summary['confidence']:.0%}")
        print(f"   🤖 Generated by: {agent.executive_summary['generated_by']}")
        print(f"\n   Summary preview:")
        print(f"   {agent.executive_summary['summary'][:200]}...")
    except AssertionError as e:
        print(f"   ❌ Executive summary validation failed: {e}")
        return False
    except Exception as e:
        print(f"   ❌ Executive summary check failed: {e}")
        return False
    
    # Test 6: Cross-Candidate Insights
    print("\n6️⃣ Checking Cross-Candidate Insights...")
    try:
        assert agent.cross_candidate_insights is not None, "Insights is None"
        assert 'insights' in agent.cross_candidate_insights, "Missing insights field"
        assert 'percentiles' in agent.cross_candidate_insights, "Missing percentiles"
        
        insights = agent.cross_candidate_insights['insights']
        percentiles = agent.cross_candidate_insights['percentiles']
        
        print(f"   ✅ Generated {len(insights)} strategic insights")
        print(f"   ✅ Calculated percentiles for {len(percentiles)} candidates")
        
        if insights:
            print(f"\n   Sample insight:")
            insight = insights[0]
            print(f"   [{insight['severity'].upper()}] {insight['title']}")
            print(f"   {insight['description']}")
    except AssertionError as e:
        print(f"   ❌ Insights validation failed: {e}")
        return False
    except Exception as e:
        print(f"   ❌ Insights check failed: {e}")
        return False
    
    # Test 7: Predictive Recommendations
    print("\n7️⃣ Checking Predictive Recommendations...")
    try:
        assert agent.predictive_recommendations is not None, "Recommendations is None"
        assert len(agent.predictive_recommendations) > 0, "No recommendations generated"
        
        print(f"   ✅ Generated recommendations for {len(agent.predictive_recommendations)} candidates")
        
        # Check top 3
        print(f"\n   Top 3 Recommendations:")
        for i, c in enumerate(ranked[:3], 1):
            pred = agent.predictive_recommendations[c.candidate_id]
            print(f"   {i}. {c.name}")
            print(f"      Recommendation: {pred['recommendation'].upper()}")
            print(f"      Confidence: {pred['confidence']:.0%}")
            print(f"      Reasoning: {pred['reasoning']}")
    except AssertionError as e:
        print(f"   ❌ Recommendations validation failed: {e}")
        return False
    except Exception as e:
        print(f"   ❌ Recommendations check failed: {e}")
        return False
    
    # Test 8: Export
    print("\n8️⃣ Testing export...")
    try:
        results = agent.export_results()
        
        assert 'ai_insights' in results, "Missing ai_insights in export"
        assert 'executive_summary' in results['ai_insights'], "Missing executive_summary"
        assert 'cross_candidate_insights' in results['ai_insights'], "Missing cross_candidate_insights"
        assert 'predictive_recommendations' in results['ai_insights'], "Missing predictive_recommendations"
        
        print("   ✅ Export includes all AI insights")
        print(f"   ✅ Version: {results['metadata']['version']}")
        
        # Test JSON serialization
        import json
        json_str = json.dumps(results, indent=2)
        print(f"   ✅ JSON serialization successful ({len(json_str)} bytes)")
        
    except AssertionError as e:
        print(f"   ❌ Export validation failed: {e}")
        return False
    except Exception as e:
        print(f"   ❌ Export failed: {e}")
        return False
    
    # Success!
    print("\n" + "=" * 60)
    print("🎉 ALL TESTS PASSED!")
    print("=" * 60)
    print("\n✅ AI-Native HR Agent is ready for the hackathon!")
    print("\n📝 Next steps:")
    print("   1. Run: streamlit run app_ai_native.py")
    print("   2. Test with full dataset (1200 candidates)")
    print("   3. Verify LLM integration with Gemini API key")
    print("   4. Practice demo presentation")
    
    return True

if __name__ == "__main__":
    success = test_ai_native()
    sys.exit(0 if success else 1)
